### ISSUE TITLE
Do not require all supported languages to be specified in YAML files

### ISSUE THREAD

**Issue by freitass** [cross-language-cpp/djinni-generator#48]
Djinni generator currently fails to parse a YAML file unless all of the supported languages are specified; there's an unhandled exception `java.util.NoSuchElementException: key not found: <key>` for any missing field (as can be seen in [this run](https://github.com/cross-language-cpp/djinni-support-lib/runs/2424293948)). This issue becomes more relevant as more languages get supported by the generator.

**Comment by paulo-coutinho** [comment]
Hi,

After upgrade to version 0.5.0 and generate my files i get error:

```
![image](https://user-images.githubusercontent.com/395096/116300362-30ff9300-a775-11eb-850f-1ba2ed8160b2.png)
```

```
Exception in thread "main" java.util.NoSuchElementException: key not found: translator
	at scala.collection.immutable.Map$EmptyMap$.apply(Map.scala:107)
	at scala.collection.immutable.Map$EmptyMap$.apply(Map.scala:105)
	at djinni.YamlGenerator$.metaFromYaml(YamlGenerator.scala:227)
	at djinni.resolver.package$.$anonfun$resolve$1(resolver.scala:52)
	at djinni.resolver.package$.$anonfun$resolve$1$adapted(resolver.scala:38)
	at scala.collection.LinearSeqOptimized.foreach(LinearSeqOptimized.scala:75)
	at scala.collection.LinearSeqOptimized.foreach$(LinearSeqOptimized.scala:72)
	at scala.collection.mutable.MutableList.foreach(MutableList.scala:33)
	at djinni.resolver.package$.resolve(resolver.scala:38)
	at djinni.Main$.main(Main.scala:363)
	at djinni.Main.main(Main.scala)
COMMAND: /Users/paulo/Developer/workspaces/cpp/ubook-sdk-mobile/build/gluecode/djinni --java-out generated-src/java/com/ubook/domain --java-package com.ubook.domain --ident-java-field mFooBar --java-implement-android-os-parcelable true --cpp-out generated-src/cpp/ubook/domain/ --cpp-namespace ubook::domain --cpp-include-prefix ubook/domain/ --ident-cpp-field fooBar --ident-cpp-method fooBar --ident-cpp-file FooBar --ident-cpp-local fooBar --ident-jni-class UBDomainFooBar --ident-jni-file UBDomainFooBar --jni-include-cpp-prefix ubook/domain/ --jni-include-prefix com/ubook/domain/ --jni-out generated-src/jni/com/ubook/domain --objc-out generated-src/objc/ubook/domain/ --objc-type-prefix UBDomain --objc-include-prefix ubook/domain/ --objcpp-include-cpp-prefix ubook/domain/ --objcpp-include-prefix ubook/domain/ --objcpp-out generated-src/objc/ubook/domain/ --yaml-out yaml --idl proj.djinni
WORKING DIR: /Users/paulo/Developer/workspaces/cpp/ubook-sdk-mobile/files/gluecode/app-domain

```

**Comment by jothepro** [comment]
Yep @paulo-coutinho, that's the problem... 😞  Since 0.5.0 all yaml files are required to also define a C# type definition. 

If the yaml files are generated by djinni, I guess you could fix this by regenerating them.

If they are handwritten, you could temporarily fix this by adding a placeholder like this for each type defined in yaml:
```yaml
cs:
  translator: 'coming soon'
  header: 'coming soon'
  typename: 'coming soon'
  reference: false
```

If you are not interested in the newly added C# support in v0.5.0, I recommend you to downgrade to v0.3.2 or v0.4.0 and wait until we provide a fix for this issue.

**Comment by paulo-coutinho** [comment]
Hi,

Yes, im using version 0.3.2 until it be solved. I have hundreds of files.

Thanks anyway.

**Comment by paulo-coutinho** [comment]
Nice. Thanks.
